% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{dutch}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\usepackage{setspace}
\onehalfspacing
\usepackage{float}
\let\origfigure\figure
\let\endorigfigure\endfigure
\renewenvironment{figure}[1][2] {
    \expandafter\origfigure\expandafter[H]
} {
    \endorigfigure
}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={My Awesome Catchy Title!},
  pdflang={nl},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{My Awesome Catchy Title!}
\author{Kasthury Inparajah \(^1\), Willem-DaniC+l Visser \(^1\), Cheyenne Brouwer \(^1\), Demi van `t Oever \(^1\),\\
Michiel Noback \(^1\), Fenna Feenstra \(^1\)\\
\(^1\)Hanzehogeschool,}
\date{}

\begin{document}
\maketitle
\begin{abstract}
Geef hier je samenvatting in maximaal 150 woorden. Het is een samenvatting van het hele artikel; niet alleen de resultaten! Begin met het belang van dit onderzoek, dan hoe het onderzoek is aangepakt en de belangrijkste resultaten en eindig met de implicaties ervan voor de wetenschap/de maatschappij. Neem nooit figuren of tabellen op in de samenvatting.
\end{abstract}

\hypertarget{introductie}{%
\section{Introductie}\label{introductie}}

\hypertarget{materialen-en-methoden}{%
\subsection{Materialen en Methoden}\label{materialen-en-methoden}}

Op de github voor dit onderzoek:
\url{https://github.com/cheyennebrouwer/eyeresearch}, staat het protocol
voor het verzamelen van de oogdata. De analisten hebben verschillende
notitie software gebruikt voor data notitie: Google Docs{[}\ref{g-docs}{]}
door analist 8075, Apple notities{[}\ref{a-notes}{]} door analist 5609,
Keep My Notes{[}\ref{keep-my-notes}{]} door analist 9308 en {[}meer{]}. Hierin
hebben de analisten op 2 dagen de metingen genoteerd. Op de dag van de
metingen zijn de analisten subject groepjes(2-7) gaan vragen of deze
wouden meedoen met het onderzoek. Bij instemming is er gevraagd naar
sexe en leeftijd en zijn de analisten de ogen van de subject met zijn
allen tegelijk gaan bekijken waarbij 1 of meer van de analisten er een
referentie blaadje bij hielden. Deze staat ook in de Github. De
subjecten zijn 1 voor 1 gevraagd of ze mee wouden doen en naar
bijhorende gegevens, tot alle subjecten zijn gemeten en de volgende
groep werd aangesproken.

De analisten vulden soms twee kleuren in of een kleur karakteristiek,
zoals: donker of licht. Op dag 1 is er op de studentencampus, de
Hanzehogeschool Groningen; Zerniekeplein 11, binnen in het gebouw ``Van
Doorenveste'' gemeten (Groningen 1). Op dezelfde dag is er in het centrum
van Groningen (Groningen 2) gemeten. Op een dag 2 is vervolgens in het
centrum van Zwolle (Zwolle) gemeten. Op alle drie locaties was het
zonnig weer op het moment van metingen. Ook was het onder schooltijd
voor de meeste MBO en HBO studenten. Op locatie Groningen 1 was de licht
conditie niet constant met variC+rende daglicht reflectie, licht
temperaturen en licht amplitude. Er waren geen licht condities die de
oogkleur bepaling onmogelijk/erg moeilijk heeft gemaakt, aldus de
analisten. Op locaties Groningen 2 en Zwolle is niet rechtstreeks
richting de zon gekeken bij het bepalen van de oogkleur. Wel is er zowel
in zon als schaduw gemeten.

Toen de metingen klaar waren werden alle metingen verzameld door 1 van
de analisten en verwerkt zodat de dubbele kleuren door de analisten
genoteerd resulteren tot enkele kleuren. De verwerkte data is in tidy
vorm gezet met de functie \texttt{pivot\_longer()}` uit de tidyr
package{[}\ref{tidyr}{]} in de programmeertaal R{[}\ref{r-lang}{]}. Het
resultaat is opgeslagen in een nieuw bestand en zijn analyses mee
gedaan.

De analyses zijn gedaan in R-studio{[}\ref{r-studio}{]} en de
programmeertaal R, met de libraries: plyr{[}\ref{plyr}{]},
dyplyr{[}\ref{dplyr}{]}, ggplot2{[}\ref{ggplot2}{]} en knitr{[}\ref{knitr}{]} van
de tidyverse collectie. Met \texttt{plyr} en \texttt{dyplyr} is dataverwerking gedaan,
zo kon er analyse worden gedaan op gefilterde delen van de data. Met
\texttt{ggplot} zijn vervolgens grafieken gemaakt. Voor de analyse van de
meetfout tussen de analisten is de functie \texttt{chisq.test} van R gebruikt,
voor een two-way chi-square test, tussen met de factoren analist en
oogkleur, met daarvoor alle gemeten personen met een of meer lege velden
weggehaald. De analyse voor de verschillen tussen de drie meet locaties
en verschillen tussen sexe is eerst de data zonder meerderheid onder de
analisten als ``undefined'' neergezet, om zo aan te geven dat er geen
definitieve oogkleur valt te bepalen. Toen werd de \texttt{CrossTable} voor de
chi-square test en nog andere statistische waarden gebruikt. Hierbij is
de locatie in groepjes gezet op basis van subject id en opgezet tegen de
oogkleur. En de sexe ook opgezet tegen de oogkleur. Als analyse voor de
vergelijking van de percentages van de gemeten kleuren zijn de deze
uitgerekend en vergeleken met die van de literatuur. Bij deze analyse is
eerst ook de data waar geen meerderheid is als ``undefined'' neergezet.

\hypertarget{resultaten}{%
\section{Resultaten}\label{resultaten}}

van mij

Content:

- verschil tussen analisten

- verschil met populatie in Nederland

- verschil tussen locaties

- verschil met mannen en vrouwen

\hypertarget{verschil-tussen-analisten}{%
\subsection{Verschil tussen analisten}\label{verschil-tussen-analisten}}

\begin{longtable}[t]{l|r|r|r|r}
\caption{\label{tab:analist-oogkleur-chi-square}De geobserveerde aantal oogkleuren links+rechts per analist.}\\
\hline
  & blauw & groen & bruin & hazel\\
\hline
9308 & 132 & 20 & 60 & 18\\
\hline
2193 & 125 & 22 & 64 & 19\\
\hline
5609 & 114 & 38 & 58 & 20\\
\hline
8705 & 110 & 36 & 72 & 12\\
\hline
\end{longtable}

\begin{verbatim}
## Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
## returning NA

## Warning in mean.default(X[[i]], ...): argument is not numeric or logical:
## returning NA
\end{verbatim}

\begin{longtable}[t]{l|r|r|r|r}
\caption{\label{tab:analist-oogkleur-chi-square}De geobserveerde aantal oogkleuren links+rechts per analist groep.}\\
\hline
groep & blauw & groen & bruin & hazel\\
\hline
5609 \& 8705 & 112.0 & 37 & 65 & 16.0\\
\hline
9308 \& 2193 & 128.5 & 21 & 62 & 18.5\\
\hline
\end{longtable}

Hier is te zien een tabel met het totale aantal metingen per oogkleur
per analist. Hieruit blijkt er geen significant verschil te zijn tussen
alle de analisten samen(p-waarde = 0,07672, N1\{FEM\} = ,05). Tussen de
analisten 9308 en 8705 was wel een significant verschil (p-waarde =
0,03118, N1\{FEM\} = ,05). Dit zie je ook aan de flinke verschillen bij
hazel(\textasciitilde33,3\%), groen(\textasciitilde44,6\%). Groen had het grootste verschil tussen
de laagste tellingen en hoogste tellingen: 52,6\% verschil. Groen was ook
met 9 de oogkleur met de grootste deviatie. Daarnaast is te zien aan de
tabel dat de bovenste twee analisten en onderste twee analisten beide
groepen vormen, aangezien ze dicht bij elkaar liggen. Hierop is nog een
\texttt{chi-square} test op los gelaten. Hier is de p-waarde 0,008905(N1\{FEM\} =
,05). Dus is er een redelijk flink significant verschil tussen de
bovenste twee en onderste twee analisten. Uit dit alles blijkt er geen
ernstige meetfout te zitten en kan er een vergelijking worden gedaan met
de bestaande gegevens over heel Nederland om te kijken of er een
systematische meetfout is of er een verschil zit tussen Nederland breed
en de locaties die hier zijn onderzocht.

\hypertarget{verschil-met-populatie-nederland}{%
\subsection{Verschil met populatie Nederland}\label{verschil-met-populatie-nederland}}

\begin{figure}
\includegraphics[width=1\linewidth]{eyecolor_files/figure-latex/plot-data-literatuur-verg-1} \caption{Oogkleuren tegenover frequenties. Het totaal aantal waarnemingen van het rechteroogkleur. De door meerderheid waargenomen kleur onder analisten. NA als er geen meerderheid was.}\label{fig:plot-data-literatuur-verg}
\end{figure}

Hier is te zien hoe blauw(52,5 \%) een meerder deel van de metingen
uitmaakt, gevolgd door bruin(34,16667 \%) en groen(8,333333 \%). Zonder
NA-waarden komt dat neer op de verhoudingen blauw, bruin, groen (55,26\%,
35,96\% en 8,77\%).

\begin{figure}
\includegraphics[width=1\linewidth]{eyecolor_files/figure-latex/plot-litr_data-data-literatuur-verg-1} \caption{Oogkleur tegen percentages voor data uit literatuur en dit onderzoek. Meerderheid waargenomen door analisten van het rechter oogkleur. Oogkleur percentages uit fsigenetics - "True colors: A literature review on the spatial distribution of eye and hair pigmentation" via researchgate}(\#fig:plot-litr_data-data-literatuur-verg)
\end{figure}

In de barplot hierboven staat data uit een paper die informatie over de
verdeling van de oog- en haarkleur te verzamelen over populaties en deze
data als een blue print te gebruiken om de nauwkeurigheid van
voorspellingen op basis van DNA te verbeteren.(Maria-Alexandra Katsara 2019) Dit
onderzoek heeft meerdere datasets, waaruit 3 percentages zijn gehaald
voor vergelijking met dit onderzoek. De blauw(60.9\%) was hieruit de
meest voorkomende volgens de literatuur meer dan dit onderzoek
suggereert. Bruin is Nederland breed minder prevalant dan bij dit
onderzoek en bij groen is dit andersom. Om antwoord te krijgen op de of
de hanze aanleg heeft voor een bepaalde oogkleur zijn ook nog de
locaties vergeleken.

\hypertarget{verschil-tussen-locaties}{%
\subsection{Verschil tussen locaties}\label{verschil-tussen-locaties}}

\includegraphics[width=1\linewidth]{eyecolor_files/figure-latex/hanze-pie-chart-1}

\hypertarget{discussie-en-conclusies}{%
\section{Discussie en Conclusies}\label{discussie-en-conclusies}}

\hypertarget{online-bijlagen}{%
\section{Online bijlagen}\label{online-bijlagen}}

\hypertarget{notitie-software}{%
\subsection{Notitie software}\label{notitie-software}}

\hypertarget{g-docs}{%
\subsubsection{Google Docs}\label{g-docs}}

Gebruikte versie: 1.23.162.05.90

Referentie:
\url{https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.sheets\&pli=1}

\hypertarget{a-notes}{%
\subsubsection{Apple notities}\label{a-notes}}

Gebruikte versie: geen data

Referentie: \url{https://apps.apple.com/us/app/notes/id1110145109}

\hypertarget{keep-my-notes}{%
\subsubsection{Keep My Notes}\label{keep-my-notes}}

Gebruikte versie: 1.80.180

Referentie: \url{https://www.keepmynotes.app/}

\hypertarget{r-lang}{%
\subsection{R}\label{r-lang}}

Gebruikte versie: 4.3.0

Referentie: \url{https://www.r-project.org/}

\hypertarget{r-libraries}{%
\subsection{R libraries}\label{r-libraries}}

\hypertarget{plyr}{%
\subsubsection{plyr}\label{plyr}}

Gebruikte versie: 1.8.8

Referentie:
\url{https://www.rdocumentation.org/packages/plyr/versions/1.8.8}

\hypertarget{dplyr}{%
\subsubsection{dplyr}\label{dplyr}}

Gebruikte versie: 1.1.2

Referentie:
\url{https://www.rdocumentation.org/packages/dplyr/versions/1.0.10}

\hypertarget{ggplot2}{%
\subsubsection{\texorpdfstring{\textbf{ggplot2}}{ggplot2}}\label{ggplot2}}

Gebruikte versie: 3.4.2

Referentie:
\url{https://www.rdocumentation.org/packages/ggplot2/versions/3.4.2}

\hypertarget{knitr}{%
\subsubsection{\texorpdfstring{\textbf{knitr}}{knitr}}\label{knitr}}

Gebruikte versie: 1.43

Referentie:
\url{https://www.rdocumentation.org/packages/knitr/versions/1.43}

\hypertarget{tidyr}{%
\subsubsection{tidyr}\label{tidyr}}

Gebruikte versie: 1.3.0

Referentie: \url{https://cran.r-project.org/web/packages/tidyr/index.html}

\hypertarget{software-tools}{%
\subsection{Software Tools}\label{software-tools}}

\hypertarget{r-studio}{%
\subsubsection{R-studio}\label{r-studio}}

Gebruikte versie: 2023.03.0 (Windows en MacOS versies)

Gebruiksreden: Het ontwikkelen van R code voor de analyse van de data.

Referentie: \url{https://posit.co/products/open-source/rstudio/}

\hypertarget{referenties}{%
\section*{Referenties}\label{referenties}}
\addcontentsline{toc}{section}{Referenties}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-Katsara2019tc}{}}%
Maria-Alexandra Katsara, Michael Nothnagel. 2019. {`True colors: A literature review on the spatial distribution of eye and hair pigmentation'} 39.

\end{CSLReferences}

\end{document}
